import type { Metadata } from "next";
import Navbar from "@/components/common/Navbar";
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MainPageLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Navbar />
            {children}
        </>
    );
}
