import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/common/Footer";
import ScrollWrapper from "@/components/common/ScrollWrapper";
import Navbar from "@/components/common/Navbar";

const poppins = Poppins({
  weight: ['100', "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}antialiased`}
      >
        <ScrollWrapper>
          {children}
        </ScrollWrapper>
      </body>
    </html>
  );
}
