import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/common/Footer";
import ScrollWrapper from "@/components/common/ScrollWrapper";
import Navbar from "@/components/common/Navbar";
import ReduxProvider from "./providers/ReducProvider";
import AuthInit from "@/components/common/AuthInit";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  weight: ['100', "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}antialiased`}
      >
        <ReduxProvider>
          <AuthInit />
          <Toaster />
          <ScrollWrapper>
            {children}
          </ScrollWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
